# Generated by Django 4.0.3 on 2022-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
